[package]
name = "spade-upload"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serialport = "4.6.1"
spade-serial = { version = "0.1.0", path = "../spade-serial" }
